var appConstants = {
  FIREBASE_URL: "https://edqio.firebaseio.com",
  INIT_USER: "INIT_USER",
  ADD_CLASS: "ADD_CLASS",
  REMOVE_CLASS: "REMOVE_CLASS",
  ADD_TO_QUEUE: "ADD_TO_QUEUE",
  INIT_QUEUE: "INIT_QUEUE",
  RESET_USER: "RESET_USER",
  INIT_MEMBERS: "INIT_MEMBERS",
  REMOVE_STUDENT: "REMOVE_STUDENT",
  ADD_STUDENT: "ADD_STUDENT",
  SET_STUDENT_STATUS: "SET_STUDENT_STATUS"
};

module.exports = appConstants;